<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'The Gateway Antiphishing app uses a central antiphishing engine to scan web, FTP, mail and more. It protects devices connected to your network by shielding users from malicious links detected by the engine.';
$lang['antiphishing_app_name'] = 'Gateway Antiphishing';
$lang['antiphishing_app_tooltip'] = 'Even the most savvy Internet users can accidentally click on a phishing link.  We recommend leaving all antiphishing features enabled.';
$lang['antiphishing_block_cloaked'] = 'Block Cloaked URLs';
$lang['antiphishing_block_ssl_mismatch'] = 'Block SSL Mismatch';
$lang['antiphishing_heuristics_engine'] = 'Heuristic Engine';
$lang['antiphishing_signature_engine'] = 'Signature Engine';
