<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'Приложение "Антифишинг" использует центральный механизм антифишинга, чтобы отсканировать сеть, FTP, почту и т.д. Это защищает устройства, соединенные с вашей сетью, защищая пользователей от вредоносных ссылок, обнаруженных этим механизмом.';
$lang['antiphishing_app_name'] = 'Антифишинг';
$lang['antiphishing_app_tooltip'] = 'Даже самые продвинутые пользователи интернета могут случайно нажать на ссылку фишинг. Мы рекомендуем оставить все функции Антифишинга включенными.';
$lang['antiphishing_block_cloaked'] = 'Блокировать скрытый URLs';
$lang['antiphishing_block_ssl_mismatch'] = 'Блокировать SSL несоответствие';
$lang['antiphishing_heuristics_engine'] = 'Эвристический механизм';
$lang['antiphishing_signature_engine'] = 'Механизм сигнатур';
