<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'The Gateway Antiphishing app uses a central antiphishing engine to scan web, FTP, mail and more. It protects devices connected to your network by shielding users from malicious links detected by the engine.';
$lang['antiphishing_app_name'] = 'Gateway Antiphishing';
$lang['antiphishing_app_tooltip'] = 'Även de mest vana Internetanvändarna kan av misstag klicka på en länk för nätfiske.  Vi rekommenderar att alla antinätfisksåtgärder är aktiva.';
$lang['antiphishing_block_cloaked'] = 'Blockera falska URL:er';
$lang['antiphishing_block_ssl_mismatch'] = 'Blockera SSL som inte matchar';
$lang['antiphishing_heuristics_engine'] = 'Heuristisk motor';
$lang['antiphishing_signature_engine'] = 'Signaturmotor';
