<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'The Gateway Antiphishing app uses a central antiphishing engine to scan web, FTP, mail and more. It protects devices connected to your network by shielding users from malicious links detected by the engine.';
$lang['antiphishing_app_name'] = 'Antiphishing gateway';
$lang['antiphishing_app_tooltip'] = 'Zelfs de meest ervaren Internet gebruikers kunnen per ongeluk op een phishing-link klikken. We raden u aan alle antiphishing functies in te schakelen.';
$lang['antiphishing_block_cloaked'] = 'Blokkeer verhulde URLs ';
$lang['antiphishing_block_ssl_mismatch'] = 'Blokkeer verkeerde SSL combinaties ';
$lang['antiphishing_heuristics_engine'] = 'Heuristic Engine';
$lang['antiphishing_signature_engine'] = 'Signature Engine';
