<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'The Gateway Antiphishing app uses a central antiphishing engine to scan web, FTP, mail and more. It protects devices connected to your network by shielding users from malicious links detected by the engine.';
$lang['antiphishing_app_name'] = 'Antiphishing bramy sieciowej';
$lang['antiphishing_app_tooltip'] = 'Nawet najbardziej ostrożni użytkownicy mogą niechcący kliknąć w link wyłudzający informacje. Zalecamy pozostawienie włączonych wszystkich funkcji antiphisingowych.';
$lang['antiphishing_block_cloaked'] = 'Blokowanie ukrytych URLi';
$lang['antiphishing_block_ssl_mismatch'] = 'Blokowanie niedopasowań SSL';
$lang['antiphishing_heuristics_engine'] = 'Silnik heurystyczny';
$lang['antiphishing_signature_engine'] = 'Silnik sygnatur';
