<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'Aplikacja bramy antiphishingowej używa centralnego mechanizmu do skanowania stron internetowych, FTP, poczty, itp. Ochrania on urządzenia podłączone do sieci blokując podejrzane linki wykryte przez system.';
$lang['antiphishing_app_name'] = 'Antiphishing bramy sieciowej';
$lang['antiphishing_app_tooltip'] = 'Nawet najbardziej ostrożni użytkownicy mogą niechcący kliknąć w link wyłudzający informacje. Zalecamy pozostawienie włączonych wszystkich funkcji antiphisingowych.';
$lang['antiphishing_block_cloaked'] = 'Blokowanie ukrytych URLi';
$lang['antiphishing_block_ssl_mismatch'] = 'Blokowanie niedopasowań SSL';
$lang['antiphishing_heuristics_engine'] = 'Silnik heurystyczny';
$lang['antiphishing_signature_engine'] = 'Silnik sygnatur';
